import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

def load_and_clean_mandi_data(filepath, market_name):
    """
    Loads raw Agmarknet/CEDA CSV data, parses dates, and isolates modal prices.
    """
    if not os.path.exists(filepath):
        raise FileNotFoundError(f"Missing raw data file at: {filepath}")

    df = pd.read_csv(filepath)

    # Standardize column naming conventions (adjust based on your raw CSV header)
    df.columns = [col.lower().strip().replace(' ', '_') for col in df.columns]

    # Ensure uniform date parsing
    df['date'] = pd.to_datetime(df['date'])

    # Filter strictly for the targeted market node
    df = df[df['market_name'].str.lower() == market_name.lower()]

    # Deduplicate if multiple grades are reported on the same day (take daily average modal price)
    df = df.groupby('date')['modal_price'].mean().reset_index()
    df.rename(columns={'modal_price': f'price_{market_name.lower()}'}, inplace=True)

    return df.set_index('date')

def pipeline_data_alignment(hub_path, local_path, hub_name, local_name):
    print("[*] Initializing data ingestion pipeline...")

    # 1. Load dataframes
    df_hub = load_and_clean_mandi_data(hub_path, hub_name)
    df_local = load_and_clean_mandi_data(local_path, local_name)

    # 2. Merge on a continuous uniform daily timeline to expose missing tracking intervals
    start_date = min(df_hub.index.min(), df_local.index.min())
    end_date = max(df_hub.index.max(), df_local.index.max())
    full_timeline = pd.date_range(start=start_date, end=end_date, freq='D')

    master_df = pd.DataFrame(index=full_timeline)
    master_df = master_df.join(df_hub).join(df_local)
    master_df.index.name = 'date'

    # 3. Analyze and flag severe reporting gaps before filling
    for col in master_df.columns:
        missing_mask = master_df[col].isna()
        # Find consecutive missing blocks using pandas grouping
        gap_groups = missing_mask.groupby((~missing_mask).cumsum())
        max_gap = gap_groups.sum().max()
        print(f"[!] Target series '{col}' displays a maximum consecutive gap of: {max_gap} days.")

        # Highlight gaps greater than 3 days in the console for your journal entries
        large_gaps = gap_groups.sum()[gap_groups.sum() > 3].count()
        if large_gaps > 0:
            print(f"    [Warning] Found {large_gaps} instances where data staled for > 3 consecutive days.")

    # 4. Handle missing market days cleanly via forward fill (stating price logic holds until updated)
    master_df.ffill(inplace=True)
    master_df.dropna(inplace=True) # Drop early head truncation if one market started later

    # 5. Engineering baseline analytical values
    col_hub = f'price_{hub_name.lower()}'
    col_local = f'price_{local_name.lower()}'

    # Spatial price spread computation
    master_df['spatial_spread'] = master_df[col_local] - master_df[col_hub]

    # Compute day-over-day returns to isolate structural price shocks
    master_df['returns_hub'] = master_df[col_hub].pct_change()
    master_df['returns_local'] = master_df[col_local].pct_change()

    # Replace infinite values generated by zero base divisions, drop resulting NaNs
    master_df.replace([np.inf, -np.inf], np.nan, inplace=True)
    master_df.dropna(inplace=True)

    return master_df

def generate_diagnostic_plots(df, hub_col, local_col, output_dir):
    os.makedirs(output_dir, exist_ok=True)
    plt.style.use('seaborn-v0_8-whitegrid' if 'seaborn-v0_8-whitegrid' in plt.style.available else 'default')

    fig, ax1 = plt.subplots(figsize=(12, 6), dpi=300)

    ax1.plot(df.index, df[hub_col], label=f'Hub Price ({hub_col})', color='#1f77b4', alpha=0.85, linewidth=1.5)
    ax1.set_xlabel('Timeline')
    ax1.set_ylabel('Hub Price (INR/Quintal)', color='#1f77b4')
    ax1.tick_params(axis='y', labelcolor='#1f77b4')

    ax2 = ax1.twinx()
    ax2.plot(df.index, df[local_col], label=f'Local Price ({local_col})', color='#ff7f0e', alpha=0.85, linewidth=1.5)
    ax2.set_ylabel('Local Price (INR/Quintal)', color='#ff7f0e')
    ax2.tick_params(axis='y', labelcolor='#ff7f0e')

    plt.title('Figure 1: Comparative Temporal Price Series Distribution', fontsize=14, pad=15)
    fig.tight_layout()

    output_path = os.path.join(output_dir, 'fig_01_raw_prices.png')
    plt.savefig(output_path, dpi=300)
    print(f"[+] Diagnostic visual metric successfully compiled to: {output_path}")

if __name__ == "__main__":
    # Configure path references mapping inside your workspace
    RAW_DIR = "data/raw"
    PROCESSED_DIR = "data/processed"
    FIG_DIR = "figures"

    os.makedirs(RAW_DIR, exist_ok=True)
    os.makedirs(PROCESSED_DIR, exist_ok=True)

    # Mocks or expects files: data/raw/azadpur_delhi.csv and data/raw/imphal_manipur.csv
    HUB_FILE = os.path.join(RAW_DIR, "azadpur_delhi.csv")
    LOCAL_FILE = os.path.join(RAW_DIR, "imphal_manipur.csv")

    try:
        cleaned_master = pipeline_data_alignment(
            hub_path=HUB_FILE,
            local_path=LOCAL_FILE,
            hub_name="azadpur",
            local_name="imphal"
        )

        # Save structural target frame
        output_csv = os.path.join(PROCESSED_DIR, "aligned_market_returns.csv")
        cleaned_master.to_csv(output_csv)
        print(f"[+] Clean unified dataset written to: {output_csv}")

        # Generate Figure 1
        generate_diagnostic_plots(cleaned_master, "price_azadpur", "price_imphal", FIG_DIR)

    except FileNotFoundError as e:
        print(f"[x] Pipeline stopped: Ensure your raw data downloads exist in '{RAW_DIR}/'.")
        print(f"    Detail: {e}")
